# Generated by Django 5.0 on 2024-09-07 03:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('gppa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=750, null=True)),
                ('year_start', models.DateField(blank=True)),
                ('renewed_year', models.DateField(blank=True, null=True)),
                ('org_approved', models.BooleanField(default=False, help_text='Has the organization approved this plan?')),
                ('gppa_approved', models.BooleanField(default=False, help_text='Has GPPA approved this plan?')),
                ('is_operational', models.BooleanField(default=False, help_text='Is the plan operational?')),
                ('is_current_plan', models.BooleanField(default=False, help_text='Is the plan this valid for operations?')),
                ('latest_approval_request_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Annual Plan',
                'ordering': ['-year_start', '-created_date', '-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('disabled', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('enabled_since', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=20)),
                ('measurement_unit', models.CharField(choices=[('units', 'Units'), ('pieces', 'Pieces'), ('metres', 'Metres'), ('inches', 'Inches'), ('bundles', 'Bundles'), ('bytes', 'Bytes'), ('litres', 'Litres'), ('other', 'Other')], max_length=255)),
                ('procurement_method', models.CharField(blank=True, choices=[('single_sourcing', 'Single Sourcing'), ('rfq', 'Request For Quotations'), ('restricted_tender', 'Restricted Tender'), ('international_tender', 'International Tender'), ('not_applied', 'Not Applied'), ('rfq 2', 'Request For Quotations 2')], default='', max_length=255)),
                ('quarter_1_budget', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('quarter_2_budget', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('quarter_3_budget', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('quarter_4_budget', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(default='', max_length=100)),
                ('gppa_requirement', models.BooleanField(default=False)),
                ('procurement_method', models.CharField(choices=[('single_sourcing', 'Single Sourcing'), ('rfq', 'Request For Quotations'), ('restricted_tender', 'Restricted Tender'), ('international_tender', 'International Tender'), ('not_applied', 'Not Applied'), ('rfq 2', 'Request For Quotations 2')], max_length=100)),
            ],
            options={
                'verbose_name': 'Procurement Threshold',
            },
        ),
        migrations.CreateModel(
            name='AnnualPlanApprovalGPPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('annual_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gppa_approval_record', to='organization.annualplan')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gppa.gppauser')),
            ],
            options={
                'verbose_name': 'Annual Plan Approval - GPPA',
                'verbose_name_plural': 'Annual Plan Approval - GPPA',
            },
        ),
        migrations.CreateModel(
            name='DepartmentProcurementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
                ('items', models.ManyToManyField(related_name='plan', to='organization.planitem')),
            ],
            options={
                'ordering': ['-last_modified'],
            },
        ),
        migrations.AddField(
            model_name='annualplan',
            name='department_plans',
            field=models.ManyToManyField(blank=True, related_name='annual_plan', to='organization.departmentprocurementplan'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(default='', max_length=15)),
                ('biography', models.TextField(blank=True, default='')),
                ('job_title', models.CharField(blank=True, default='', help_text='The job title of the staff', max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'Female'), ('other', 'Other')], default='other', help_text='This is used to determine the permissions', max_length=25)),
                ('disabled', models.BooleanField(default=True, help_text="Whether staff's account is deactivated or not")),
                ('is_admin', models.BooleanField(default=False, help_text='An IT-Admin user account')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.address')),
                ('user_account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date', '-last_modified'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.staff'),
        ),
        migrations.CreateModel(
            name='AnnualPlanApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('annual_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_record', to='organization.annualplan')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.staff')),
            ],
            options={
                'verbose_name': 'Annual Plan Approval',
                'verbose_name_plural': 'Annual Plan Approval',
            },
        ),
        migrations.AddField(
            model_name='annualplan',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.staff'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('disabled', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('enabled_since', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
                ('unit_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_unit', to='organization.staff')),
            ],
            options={
                'ordering': ['-created_date', '-last_modified'],
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='unit',
            field=models.ForeignKey(help_text='The unit this staff belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='organization.unit'),
        ),
    ]
