# Generated by Django 5.0 on 2024-09-08 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Whether staff is deleted or not'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='unit',
            field=models.ForeignKey(help_text='The unit this staff belongs to', on_delete=django.db.models.deletion.CASCADE, to='organization.unit'),
        ),
    ]
