# Generated by Django 5.0 on 2024-09-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='procurement_method',
            field=models.CharField(blank=True, choices=[('single_sourcing', 'Single Sourcing'), ('rfq', 'Request For Quotations'), ('restricted_tender', 'Restricted Tender'), ('international_tender', 'International Tender'), ('not_applied', 'Not Applied'), ('rfq 2', 'Request For Quotations 2')], max_length=100, null=True),
        ),
    ]
