# Generated by Django 5.0 on 2024-09-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_staff_date_deleted_staff_is_deleted_alter_staff_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, default='other', help_text='This is used to determine the permissions', max_length=25),
        ),
    ]
