# Generated by Django 5.0 on 2024-10-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_threshold_procurement_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='An System-Admin user account'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='middle_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
