# Generated by Django 5.0 on 2024-09-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authgroup',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authgroup',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
