# Generated by Django 5.0 on 2024-10-29 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('procurement', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='rfq_response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vendors.rfqresponse'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='purchaseorderapproval',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.staff'),
        ),
        migrations.AddField(
            model_name='purchaseorderapproval',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_record', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='officer',
            field=models.ForeignKey(blank=True, help_text='Authorizes this instance', on_delete=django.db.models.deletion.CASCADE, to='organization.staff'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='officer_department',
            field=models.ForeignKey(blank=True, help_text='The department that the officer belongs to at the time of creation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department'),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to='procurement.requisition'),
        ),
        migrations.AddField(
            model_name='requisitionapproval',
            name='department_approval',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval', to='procurement.departmentrequisitionapproval'),
        ),
        migrations.AddField(
            model_name='requisitionapproval',
            name='finance_approval',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval', to='procurement.financerequisitionapproval'),
        ),
        migrations.AddField(
            model_name='requisitionapproval',
            name='procurement_approval',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval', to='procurement.procurementrequisitionapproval'),
        ),
        migrations.AddField(
            model_name='requisitionapproval',
            name='requisition',
            field=models.OneToOneField(help_text='The requisition that is being approved', on_delete=django.db.models.deletion.CASCADE, related_name='approval_record', to='procurement.requisition'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='items',
            field=models.ManyToManyField(to='procurement.requisitionitem'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='officer',
            field=models.ForeignKey(help_text='Authorizes this instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_officer', to='organization.staff'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='opened_by',
            field=models.ManyToManyField(help_text='List of staffs that opens this procurement', to='organization.staff'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='requisition',
            field=models.ForeignKey(help_text='The requisition record of which this RFQ is initiated for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq', to='procurement.requisition'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='rfq_requests', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='procurement.rfq'),
        ),
        migrations.AddField(
            model_name='rfqapproval',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_officer', to='organization.staff'),
        ),
        migrations.AddField(
            model_name='rfqapproval',
            name='rfq',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_record', to='procurement.rfq'),
        ),
        migrations.AddField(
            model_name='rfqapprovalgppa',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_officer_gppa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfqapprovalgppa',
            name='rfq',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_record_gppa', to='procurement.rfq'),
        ),
        migrations.AddField(
            model_name='rfqapproval',
            name='gppa_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_record', to='procurement.rfqapprovalgppa'),
        ),
        migrations.AddField(
            model_name='rfqcontract',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_rfq_contracts', to='organization.staff'),
        ),
        migrations.AddField(
            model_name='rfqcontract',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='procurement.rfq'),
        ),
        migrations.AddField(
            model_name='rfqcontract',
            name='rfq_response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='vendors.rfqresponse'),
        ),
        migrations.AddField(
            model_name='rfqcontract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_contracts', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='rfqcontractapproval',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_record', to='procurement.rfqcontract'),
        ),
        migrations.AddField(
            model_name='rfqcontractapproval',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_contract_approvals', to='organization.staff'),
        ),
        migrations.AddField(
            model_name='rfqcontractaward',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='procurement.rfqcontract'),
        ),
        migrations.AddField(
            model_name='rfqcontractaward',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_rfq_awards', to='organization.staff'),
        ),
        migrations.AddField(
            model_name='rfqcontractaward',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_contract_awards', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='rfqevaluation',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.staff'),
        ),
        migrations.AddField(
            model_name='rfqevaluation',
            name='rfq',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='procurement.rfq'),
        ),
        migrations.AddField(
            model_name='rfqevaluationapprover',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_record', to='procurement.rfqevaluation'),
        ),
        migrations.AddField(
            model_name='rfqevaluationapprover',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.staff'),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='rfq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.rfq'),
        ),
        migrations.AddField(
            model_name='rfqnegotiation',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation', to='procurement.rfqcontract'),
        ),
        migrations.AddField(
            model_name='rfqnegotiationnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_notification_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfqnegotiationnote',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_notes', to='procurement.rfqcontract'),
        ),
        migrations.AddField(
            model_name='rfqnegotiation',
            name='notes',
            field=models.ManyToManyField(blank=True, to='procurement.rfqnegotiationnote'),
        ),
        migrations.AddField(
            model_name='rfqquotationevaluation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='procurement.rfqitem'),
        ),
        migrations.AddField(
            model_name='rfqquotationevaluation',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.staff'),
        ),
        migrations.AddField(
            model_name='rfqquotationevaluation',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='vendors.rfqresponse'),
        ),
        migrations.AddField(
            model_name='rfqevaluation',
            name='evaluations',
            field=models.ManyToManyField(related_name='evaluation', to='procurement.rfqquotationevaluation'),
        ),
        migrations.AddField(
            model_name='unitrequisitionapproval',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_approval_officer', to='organization.staff'),
        ),
        migrations.AddField(
            model_name='requisitionapproval',
            name='unit_approval',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval', to='procurement.unitrequisitionapproval'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.staff'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.approvalstep'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.approvalworkflow'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='current_approval_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.workflowstep'),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='steps',
            field=models.ManyToManyField(related_name='workflows', through='procurement.WorkflowStep', to='procurement.approvalstep'),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='workflow_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.workflowstep'),
        ),
        migrations.AddConstraint(
            model_name='rfqquotationevaluation',
            constraint=models.UniqueConstraint(fields=('quotation', 'item'), name='unique_evaluation', violation_error_message='This quotation and item has already been evaluated.'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow', 'order')},
        ),
    ]
