# Generated by Django 5.0 on 2024-02-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='level',
            field=models.CharField(choices=[('APPROVAL LEVEL', 'Approval Level'), ('PUBLISH LEVEL', 'Publish Level'), ('QUOTATION LEVEL', 'Quotation Level'), ('EVALUATION LEVEL', 'Evaluation Level'), ('CONTRACT LEVEL', 'Contract Level'), ('PURCHASE ORDER LEVEL', 'Purchase Order Level'), ('INVOICE LEVEL', 'Invoice Level')], default='APPROVAL LEVEL', max_length=50),
        ),
        migrations.AlterField(
            model_name='rfqnegotiationnote',
            name='validity_period',
            field=models.DateTimeField(null=True),
        ),
    ]
