# Generated by Django 5.0 on 2024-11-02 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('procurement', '0003_rfq_published_at'),
        ('vendors', '0004_vendor_short_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AWARDED', 'Awarded'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.staff')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.rfqresponse')),
            ],
        ),
        migrations.CreateModel(
            name='ContractAwardApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approve', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.staff')),
                ('award', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='procurement.contractaward')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
