# Generated by Django 5.0 on 2024-09-28 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_threshold_procurement_method'),
        ('procurement', '0003_alter_rfq_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqcontractapproval',
            name='officer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rfq_contract_approvals', to='organization.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfqcontractapproval',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
