# Generated by Django 5.0 on 2024-10-22 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_threshold_procurement_method'),
        ('procurement', '0004_rfqcontractapproval_officer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='officer_department',
            field=models.ForeignKey(blank=True, help_text='The department that the officer belongs to at the time of creation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department'),
        ),
        migrations.AlterField(
            model_name='departmentrequisitionapproval',
            name='approve',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='no', max_length=255),
        ),
        migrations.AlterField(
            model_name='financerequisitionapproval',
            name='approve',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='no', max_length=255),
        ),
        migrations.AlterField(
            model_name='procurementrequisitionapproval',
            name='approve',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorderapproval',
            name='approve',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=255),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='requisitionapproval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfqapproval',
            name='approve',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfqapprovalgppa',
            name='approve',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfqcontract',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfqcontractapproval',
            name='approve',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='rfqevaluationapprover',
            name='approve',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=100),
        ),
        migrations.AlterField(
            model_name='unitrequisitionapproval',
            name='approve',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='no', max_length=255),
        ),
    ]
