# Generated by Django 5.0 on 2024-11-02 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('procurement', '0005_alter_contractaward_quotation_and_more'),
        ('vendors', '0007_alter_rfqresponse_evaluation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='contracts/related_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Completed', 'Completed'), ('Terminated', 'Terminated'), ('Pending Approval', 'Pending Approval')], default='Draft', max_length=20)),
                ('payment_terms', models.TextField()),
                ('delivery_schedule', models.TextField()),
                ('terms_and_conditions', models.TextField()),
                ('confidentiality_clause', models.BooleanField(default=False)),
                ('penalty_clause', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contract_document', models.FileField(blank=True, null=True, upload_to='contracts/documents/')),
                ('approval_remarks', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contracts', to='organization.staff')),
                ('award', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='procurement.contractaward')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='vendors.vendor')),
                ('additional_documents', models.ManyToManyField(blank=True, related_name='contracts', to='procurement.contractdocument')),
            ],
        ),
        migrations.CreateModel(
            name='ContractTermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('terminated_date', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to='procurement.contract')),
            ],
        ),
    ]
