# Generated by Django 5.0 on 2024-10-23 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_approvalworkflow_alter_requisition_officer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
