# Generated by Django 5.0 on 2024-11-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_contractattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='procurement.contractattachment'),
        ),
    ]
