# Generated by Django 5.0 on 2024-10-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_alter_approvalstep_options_approvalstep_officer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
