# Generated by Django 5.0 on 2024-09-07 04:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('contact_email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, db_index=True, default='The Gambia', max_length=50)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('license_number', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_certificate_url', models.URLField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, default=False)),
                ('date_verified', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_modified', '-created_date'],
            },
        ),
    ]
