# Generated by Django 5.0 on 2024-10-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqresponse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Whether vendor accepted this requisition or rejects it', max_length=10),
        ),
    ]
