# Generated by Django 5.0 on 2024-10-30 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfqresponse',
            name='delivery_terms',
        ),
        migrations.AddField(
            model_name='rfqresponse',
            name='delivery_date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
