# Generated by Django 5.0 on 2024-10-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_rfqresponse_delivery_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqresponse',
            name='delivery_date',
            field=models.DateTimeField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rfqresponse',
            name='pricing',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rfqresponse',
            name='validity_period',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
