# Generated by Django 5.0 on 2024-11-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_rfqresponse_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='short_desc',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
