name: TEST-WORKFLOW

# This workflow is triggered on every push to the main branch
on:
  # Trigger on push to main
  push:
    # Only trigger on main
    branches:
      - main

# This is the job that will be executed
jobs:
  test:
    # The job will run on an ubuntu-latest environment
    runs-on: ubuntu-latest

    # These are the steps that will be executed
    steps:
      - name: Test The application
        run: echo "Testing application"
